# Checks the repo builds correctly once the bootstrap & init template has run...

name: Test Scripts

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-clone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install zsh
        run: sudo apt install zsh
      - name: Set up Java
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: gradle
      - name: Run boostrap script
        shell: zsh {0}
        run: ./.specmesh/bootstrap.sh "some-User-name/a_Nother-REpo_name" "some-User-name"
      - name: Check compiles & runs
        run: |
          ./gradlew check
          ./gradlew clean
      - name: Add service
        shell: zsh {0}
        run: ./.specmesh/add_service.sh my-service
      - name: Check compiles & runs
        run: |
          ./gradlew check
          ./gradlew clean
      - name: Add 2nd service
        shell: zsh {0}
        run: ./.specmesh/add_service.sh other-service
      - name: Check compiles & runs
        run: |
          ./gradlew check
          ./gradlew clean
