# Checks the repo builds correctly once the bootstrap & init template has run...

name: Test Scripts

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-clone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install zsh
        run: sudo apt install zsh
      - name: Set up Java
        uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8 # v4.1.0
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: gradle
      - name: Run boostrap script
        shell: zsh {0}
        run: ./.specmesh/bootstrap.sh "some-User-name/a_Nother-REpo_name" "some-User-name"
      - name: Check compiles & runs
        run: |
          ./gradlew check
          ./gradlew clean
      - name: Add service
        shell: zsh {0}
        run: ./.specmesh/add_service.sh my-service
      - name: Check compiles & runs
        run: |
          ./gradlew check
          ./gradlew clean
      - name: Add 2nd service
        shell: zsh {0}
        run: ./.specmesh/add_service.sh other-service
      - name: Check compiles & runs
        run: |
          ./gradlew check
          ./gradlew clean
