# Checks the repo builds correctly once the bootstrap & init template has run...

name: Test Scripts

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-clone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Install zsh
        run: sudo apt install zsh
      - name: Set up Java
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: gradle
      - name: Run boostrap script
        shell: zsh {0}
        run: ./.specmesh/bootstrap.sh "some-User-name/a_Nother-REpo_name" "some-User-name"
      - name: Check compiles & runs
        run: |
          ./gradlew check
          ./gradlew clean
      - name: Add service
        shell: zsh {0}
        run: ./.specmesh/add_service.sh my-service
      - name: Check compiles & runs
        run: |
          ./gradlew check
          ./gradlew clean
      - name: Add 2nd service
        shell: zsh {0}
        run: ./.specmesh/add_service.sh other-service
      - name: Check compiles & runs
        run: |
          ./gradlew check
          ./gradlew clean
